export const texts = [
    "Take a deep breath, relax your fingers and take it slow. You need to be focused and not annoyed when attempting the typing speed test. The best thing you can do to start typing faster is to type more. The more practice you will get under your belt, the faster your typing-fu will be. It's all about developing muscle memory. Just make sure you are reinforcing the good habits and not ones that will leave your fingers hurting after an intense typing session.",
    "The one that is the most comfortable. The more you type the faster you will get. And to type a lot, you can't feel uncomfortable. The small bumps on the F and J keys will help your fingers locate the correct position without looking. This setup should give you full range of motion. There are a few alternative layouts that propose a more ergonomic approach to typing. You could also take the big leap and try out the Dvorak keyboard but that's a whole other story.",
    'The QWERTY keyboard was designed in 1868 by Christopher - the man who invented the first successful typewriter. The order of the keys was decided by listing the most common letter combinations and making sure they are not placed next to each other. This was done to avoid jamming problems that often happened when two neighbouring keys were pressed one after another. The QWERTY keyboard is used to this day and is the most widely spread keyboard type out there.',
    'What is WPM typing test? There are different types of testing. This one is a typing test, where the typing skills are expressed in words per minute. The more you practice typing and the more you test typing speed, the higher the WPM score will be. Some online typing tests and typing test games focus only on WPM typing. The disadvantage of WPM typing test is learning only how to type fast. WPM typing tests do not tell anything on accuracy.',
    'Yes, this is a free typing test. As makers of LiveChat - customer service software for business, we wanted to provide the community of our customers and live chat agents with a free typing test. This way they can constantly practice typing and improve typing skills. You also can test your typing speed for free. Our test is a free typing test with WPM score, but it can be also used as a typing speed test for kids.',
    "Practice typing as much as you can. Type a lot, type tests, practice typing tests. Improve your words per minute typing results and often test your typing speed. Our typing speed test will keep track of all typing tests that you've taken in the past, so you will be able to see the improvements over time. You will be able to see how your speed typing has changed. If you can do a 5 minute typing test every day, your typing speed will increase dramatically!",
    "The faster you can type, the faster you will be able to communicate with others. You will be able to save a ton of time on any kind of work that requires typing. At first, it will be a couple of extra minutes that you won't really notice. Over time the minutes will turn into hours of saved time you can spend on other activities.",
];

export default { texts };
