export const MAXIMUM_USERS_FOR_ONE_ROOM = 5;
export const MINIMUM_USERS_FOR_START_GAME = 1;
export const SECONDS_TIMER_BEFORE_START_GAME = 3;
export const SECONDS_FOR_GAME = 50;
export const SECOND_LEADER_UPDATE_RATE = 30;
