export const MAXIMUM_USERS_FOR_ONE_ROOM = 5;
export const MINIMUM_USERS_FOR_START_GAME = 2;
export const SECONDS_TIMER_BEFORE_START_GAME = 12;
export const SECONDS_FOR_GAME = 150;
export const SECOND_LEADER_UPDATE_RATE = 30;
